export interface Payment {
  access_key: string,
  profile_id: string,
  signed_field_names: string,
  unsigned_field_names: string,
  locale: string,
  transaction_uuid: string,
  signed_date_time: string,
  transaction_type: string,
  reference_number: string,
  amount: string,
  currency: string,
  payment_method: string,
  bill_to_forename: string,
  bill_to_surname: string,
  bill_to_email: string,
  bill_to_phone: string,
  bill_to_address_line1: string,
  bill_to_address_city: string,
  bill_to_address_state: string,
  bill_to_address_country: string,
  bill_to_address_postal_code: string,
  card_type: string,
  card_number: string,
  card_expiry_date: string,
  signature: string
}